name: Build & Deploy to GoDaddy (FTP)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install & Build (Vite)
        run: |
          npm ci
          npm run build   # outputs to dist/

      # --- Frontend (Vite) -> site root ---
      - name: Deploy frontend (dist) to site root
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps # FTPS OK for small, static build
          port: 21
          local-dir: dist/ # deploy only the built files
          server-dir: ./ # FTP user starts in site root
          dangerous-clean-slate: false # don't touch backend/

      # --- Backend (PHP) -> /backend ---
      - name: Deploy backend (PHP) to /backend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp # more stable on GoDaddy for PHP/.htaccess
          port: 21
          local-dir: backend/ # from your repo
          server-dir: ./backend/ # into site/backend/
          dangerous-clean-slate: false # keep user data
          log-level: verbose
          exclude: |
            uploads/**
            submissions/**
            **/.env*
            **/*.log
            **/.DS_Store
            test*.php
            debug*.php
            add-test-data.php
