name: Build & Deploy to GoDaddy (FTP)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install & Build (Vite)
        run: |
          npm ci
          npm run build   # outputs dist/

      # Frontend -> site root (do NOT clean-slate)
      - name: Deploy frontend (dist) to site root
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: dist/
          server-dir: ./                         # FTP user's root = /public_html/luckyhospitality.com/
          dangerous-clean-slate: false           # <— important: don't delete backend
          exclude: |
            .well-known/**

      # Backend -> /backend (keep uploads/submissions)
      - name: Deploy backend (PHP) to /backend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: backend/
          server-dir: ./backend/
          dangerous-clean-slate: false
          exclude: |
            uploads/**
            submissions/**
            **/.env*
            **/*.log
            **/.DS_Store