name: Build & Deploy to GoDaddy (FTP)

on:
  push:
    branches: [ main ]   # change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Remove the next 2 steps if your site is pure HTML/CSS (no build step)
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install & Build
        run: |
          npm ci
          npm run build

      # Deploy only the build output (adjust local-dir if different)
      - name: Upload via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./                       # for React/Vite. If plain HTML: ./
          server-dir: public_html/luckyhospitality.com/  # adjust if needed
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
